- name: Run Database
  docker_container:
    name: database
    image: jalfonsi/database
    ports: "8090:8080"
    env:
      POSTGRES_DB: "db"
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "pwd"
    networks:
      - name: network_one
