version: '3.7'

services:
  backend:
    build:
      context: ./simple-api-student-main
      dockerfile: Dockerfile
    container_name: simple-api
    networks:
      - app-network
    depends_on:
      - database

  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name: database
    networks:
      - app-network

  httpd:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:

