version: '3.7'

services:
  backend:
    build:
      context: ./simple-api-student-main
      dockerfile: Dockerfile
    container_name: simple-api
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - database

  database:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name: database
    networks:
      - app-network

  httpd:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "8092:80"
    networks:
      - app-network
    depends_on:
      - backend
      - front
  front:
    build:
      context: ./devops-front-main
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8093:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:

